resource "okta_auth_server" "OktaCarRentalAuthServerGeneratedbyUDPausrlrvpwjpWaGWyC0h7" {
audiences = ["https://oktacarrental.com"]
description = "Okta Car Rental Auth Server (Generated by UDP)"
name = "Okta Car Rental Auth Server (Generated by UDP)"
}
