resource "okta_auth_server" "OktaCarRentalAuthServerGeneratedbyUDPausrlrvpwjpWaGWyC0h7" {
audiences = ["https://oktacarrental.com"]
description = "Okta Car Rental Auth Server (Generated by UDP)"
name = "Okta Car Rental Auth Server (Generated by UDP)"
}
resource "okta_policy_signon" "MFA00pq6kcec32M0GZAo0h7" {
status = "ACTIVE"
name = "MFA"
description = "static description"
}
