resource "okta_group" "Prospect00grr5qrgrJgGk8zl0h7" {
name = "Prospect"
description = "(Generated by UDP)"
}
resource "okta_app_oauth" "oidcclient0oarr5s230XIVWQQA0h7" {
label = "avb-second-tenant o4o Demo (Generated by UDP)"
type = "web"
grant_types = ["authorization_code"]
redirect_uris = ["https://avb-second-tenant.o4o.unidemo.online/authorization-code/avb-second-tenant"]
response_types = ["code"]
token_endpoint_auth_method = "client_secret_basic"
}
